### PR TITLE
Some information about public fuzzing of Mbed TLS

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
Arm corporate note: we're approved to contribute to the Mbed TLS integration of Cryptofuzz. We're also approved to contribute to OSS-Fuzz, but because this requires a CLA, each employee must follow an internal process, see Confluence.

**Review by Harry-Ramsey — DISMISSED** [review]
LGTM.

**Review by eleuzi01 — APPROVED** [review]
LGTM, thanks!

**Review by Harry-Ramsey — APPROVED** [review]
LGTM.

**Pull request merged**
